apiVersion: v1
kind: Service
metadata:
  name: coinbase-service
spec:
  type: LoadBalancer
  selector:
    app: coinbase
    version: green # Change this to "blue" for Blue environment.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
